In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75


# Adding a new column

### Adding a new column with a scalar value

In [3]:
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70


# Adding a new column with an array
The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [4]:
# import numpy
import numpy as np

In [6]:
# create an array of 1000 elements
language_score = np.arange(0, 1000) # gives us range that starts with first argument and to the last argument

In [7]:
language_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
# verify the length of the array because length of the array must be the same as the length of the dataframe
len(language_score)

1000

In [13]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams 

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998


In [20]:
# create random integer numbers between 1 and 100 (method-> random.randint)
int_language_score = np.random.randint(1, 100, size=1000) 
# first arg -> lowest value of the random numbers (inclusive)
# second arg -> the highest value in the random numbers (exclusive)
# third arg -> is the size 

int_language_score

array([60,  9, 67, 22, 40, 92, 69, 67, 55,  6,  8,  6, 27, 44, 66, 34, 95,
       40,  4,  7, 15, 44, 86, 49, 26, 48,  5,  8, 47, 12, 47, 95, 64, 38,
       83, 19, 73, 22, 82, 25, 56,  9, 23, 68, 84, 22, 69, 47,  9, 91,  2,
       28, 40, 52, 21, 39, 90, 39, 83,  8, 91, 13, 26, 88, 99, 65, 26, 22,
       72, 95, 79, 38, 51, 25, 78, 75, 81, 66, 91, 90, 29, 40, 20, 61, 10,
       55, 39, 65, 84, 50, 95, 93, 59, 91, 32, 82, 27, 30, 36, 73, 76, 59,
        6, 26,  2, 35, 76, 72, 39, 55, 40, 33, 90, 77, 22, 85, 77, 64, 60,
       57, 88, 66, 35,  3, 48, 16, 55, 58, 27, 78, 82, 39, 97, 30, 82, 56,
        4, 79, 70, 42,  5, 22, 57, 46, 80, 89, 84, 34, 20, 57, 86, 42, 57,
       90, 11, 21,  6, 24, 51, 51,  3, 22, 13,  6, 96, 59, 97, 38, 61, 31,
       73, 36, 55, 51, 62, 95, 45, 57,  6, 28, 56, 93, 10, 14,  5, 80, 94,
        3, 64, 36, 16, 54, 90, 69, 49, 37, 98, 15, 80, 98, 21, 91, 87, 77,
       68, 91, 19, 25, 25, 94, 39, 30, 18, 52, 56, 67, 73, 66, 15, 71, 74,
       15, 30, 69, 43, 86

In [21]:
print(len(int_language_score))

# min value inclusive and high value exclusive
print(min(int_language_score))
print(max(int_language_score))

1000
1
99


In [22]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,60
1,female,group C,some college,standard,completed,69,90,88,9
2,female,group B,master's degree,standard,none,90,95,93,67
3,male,group A,associate's degree,free/reduced,none,47,57,44,22
4,male,group C,some college,standard,none,76,78,75,40
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,59
996,male,group C,high school,free/reduced,none,62,55,55,38
997,female,group C,high school,free/reduced,completed,59,71,65,12
998,female,group D,some college,standard,completed,68,78,77,39


In [23]:
# create random float numbers between 1 and 100
np.random.uniform(1, 100, size=1000)

array([75.02969507, 65.02041467, 77.64689712, 55.5512666 , 56.69526816,
       52.6616912 , 10.07008545, 73.58813758, 92.88591364, 52.40253144,
       44.84316531, 99.62374084, 23.29977406, 84.62927136, 51.49183491,
       38.90427021, 85.33363241, 41.24977744, 51.16228419, 77.90900605,
       10.47039637, 37.60197071, 29.85475668, 85.63451255, 48.64717645,
       44.0839029 , 52.2597308 , 65.55008138, 82.27899321, 26.05148534,
       93.90670293, 24.10180065, 95.77899938, 82.20067552, 52.3501337 ,
       35.67460026, 21.64596064, 69.74739136, 85.81544739, 15.11584465,
       86.50869075, 94.72429047, 38.61570071, 46.44750537, 13.75878083,
       51.23804187, 55.09966028, 18.23995051, 19.84711845, 60.61286977,
       59.57656865, 60.74221868, 31.21012462, 99.83065781, 73.0626717 ,
       66.86767624, 47.58553998, 32.52821429, 57.01603646, 58.50258444,
       15.61317173, 23.89511783, 10.20313484, 61.90420983, 33.19807827,
       14.11863196, 41.90136863, 46.93549452, 65.58929539, 23.73